-- MySQL Script generated by MySQL Workbench
-- Tue Apr 21 14:24:26 2020
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema AlcoholMarket
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema AlcoholMarket
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `AlcoholMarket` DEFAULT CHARACTER SET utf8 ;
USE `AlcoholMarket` ;

-- -----------------------------------------------------
-- Table `AlcoholMarket`.`AlcoholDrinks`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `AlcoholMarket`.`AlcoholDrinks` (
  `idAlcoholDrinks` INT NOT NULL AUTO_INCREMENT,
  `type` ENUM("LIQUEUR", "BEER", "BITTER", "HARD_ALCOHOL", "TINCTURE", "VINE") NOT NULL,
  `name` VARCHAR(45) NOT NULL,
  `country` VARCHAR(45) NOT NULL,
  `cost` DECIMAL(5,2) NOT NULL,
  `ADV` DECIMAL(3,1) NOT NULL,
  `sugarContent` DECIMAL(3,1) NULL,
  `color` VARCHAR(45) NULL,
  `herbsQuantity` INT NULL,
  `rawMaterial` VARCHAR(45) NULL,
  `additive` VARCHAR(45) NULL,
  `isItQuiet` TINYINT(1) NULL,
  PRIMARY KEY (`idAlcoholDrinks`))
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
